name: postech-dev
services:
  # PostgreSQL - Banco de dados para os microsserviços
  postgres:
    image: postgres:16-alpine
    container_name: postech-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postech-network

  # RabbitMQ - Message Broker para comunicação assíncrona
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: postech-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "${RABBITMQ_PORT}:5672"   # AMQP protocol
      - "${RABBITMQ_MANAGEMENT_PORT}:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - postech-network

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local

networks:
  postech-network:
    driver: bridge
    name: postech-network