apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: infrastructure
data:
  01-init-databases.sql: |
    CREATE DATABASE postech_users;
    CREATE DATABASE postech_catalog;
    CREATE DATABASE postech_payments;
    CREATE DATABASE postech_notifications;

    GRANT ALL PRIVILEGES ON DATABASE postech_users TO postech_admin;
    GRANT ALL PRIVILEGES ON DATABASE postech_catalog TO postech_admin;
    GRANT ALL PRIVILEGES ON DATABASE postech_payments TO postech_admin;
    GRANT ALL PRIVILEGES ON DATABASE postech_notifications TO postech_admin;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: infrastructure
data:
  POSTGRES_DB: "postech_main"
  POSTGRES_USER: "postech_admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: infrastructure
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postech_dev_password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: infrastructure
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postech_admin", "-d", "postech_main"]
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "75m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: infrastructure
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
